/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void  make_all_rows_HIGH(void);
void check_R1(void);
void check_R2(void);
void check_R3(void);
void check_R4(void);

int main(void)
{
	//RCC AHB1 peripheral clock enable register (RCC_AHB1ENR)
	RCC_AHB1ENR_t volatile *const pClkCtrlReg 	 	= 	ADDR_REG_AHB1ENR;
	//GPIO port mode register
	GPIOx_MODE_t volatile *const pGPIODModeReg  	= 	ADDR_REG_GPIOD_MODE;
	//GPIO port pull-up/pull-down register
	GPIOx_PUPDR_t volatile *const pPullUpDownReg  	= 	ADDR_REG_GPIOD_PUPD;

	//1. Enable the clock for GPOID peripheral in the AHB1ENR (SET the 3rd bit position)
	pClkCtrlReg->gpiod_en = CLOCK_ENABLE;
	// 2.configure PD0,PD1,PD2,PD3 as output (rows)
	pGPIODModeReg->pin_0 = HIGH;
	pGPIODModeReg->pin_1 = HIGH;
	pGPIODModeReg->pin_2 = HIGH;
	pGPIODModeReg->pin_3 = HIGH;
	// 3. configure PD8 , PD9, PD10, PD11 as input (columns)
	pGPIODModeReg->pin_8  = LOW;
	pGPIODModeReg->pin_9  = LOW;
	pGPIODModeReg->pin_10 = LOW;
	pGPIODModeReg->pin_11 = LOW;
	// 4.Enable internal pull-up resistors for PD8 PD9 PD10 PD11
	pPullUpDownReg->pin_8  = HIGH;
	pPullUpDownReg->pin_9  = HIGH;
	pPullUpDownReg->pin_10 = HIGH;
	pPullUpDownReg->pin_11 = HIGH;

	while(1)
	{
	    //make all rows HIGH
		make_all_rows_HIGH();

		check_R1();


	    //make all rows HIGH
	    make_all_rows_HIGH();

	    check_R2();

	    //make all rows HIGH
	    make_all_rows_HIGH();

	    check_R3();

	    //make all rows HIGH
	    make_all_rows_HIGH();

	    check_R4();

	}

	//Configure
    /* Loop forever */
	for(;;);
}
